### ISSUE TITLE
WDT Problem solving for timeout problems

### ISSUE THREAD

**Issue by Roehrenkramladen** [Aypac/Arduino-TR-064-SOAP-Library#37]
WDT (watchdog timeout of the ESP8266 core) problems occur very often if the debug mode remains switched on. The cause is the endless debug messages in the tr064.cpp file.
If you set the debug_level to NONE in line 55 of the file, the problems are gone.
debug_level = DEBUG_NONE;
thanks

**Comment by Aypac** [comment]
Hi Roehrenkramladen,
Thanks for the input!
Just to clarify: what do you suggest to do with this info? Add it to the wiki, change something in the code, ...?

**Comment by Roehrenkramladen** [comment]
> 
> 
> Hi Roehrenkramladen,
> Thanks for the input!
> Just to clarify: what do you suggest to do with this info? Add it to the wiki, change something in the code, ...?

Hallo,

habe dir geantwortet.

Danke!

**Comment by Aypac** [comment]
Moin,
wo hast du mir geantwortet?

**Comment by Roehrenkramladen** [comment]
Hallo,

ich habe deinen Vorschlag mal getestet. Leider funktioniert es nicht. Der ESP8266 stürzt ab.
Der Login ins Wifi funktioniert, wenn er aber die TR064 Verbindung startet stürzt die Software ab.
Auslöser ist der init Prozess. Der blockiert den ESP8266 zu lange der löst dann WDT (Wachdog Timeout).
Der seriell Monitor gibt dann folgendes aus.

*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Status:
*WM: 6
*WM: Using last saved values, should be faster
*WM: Connection result:
*WM: 3
*WM: IP Address:
*WM: 192.168.178.70
Verbunden mit dem WLAN.
*WM: freeing allocated params!

User exception (panic/abort/assert)
--------------- CUT HERE FOR EXCEPTION DECODER ---------------
WDT Soft reset
Panic core_esp8266_main.cpp:133 __yield

>>>stack>>>

ctx: cont
sp: 3ffef5c0 end: 40215b4a offset: 0000
3ffef5c0:  007a1200 2e4a16ad 00000000 000005b4 
3ffef5d0:  000000fe 00000000 00000000 00000000 
3ffef5e0:  00000000 00000000 00000000 3ffeeeb0 
3ffef5f0:  00000000 00000860 40100288 000005b4 
3ffef600:  3fff45a4 3fff1014 3fff1014 4020ada2 
3ffef610:  000e5131 00000000 3fff121c 4020adff 
3ffef620:  3fff45a4 3fff1014 00000079 4020a669 
3ffef630:  3fff45a4 3fff1014 3fff1014 4020908b 
3ffef640:  00000000 00000000 00000094 402090cb 
3ffef650:  3fff45a4 3fff0c1c 00000000 00003294 
3ffef660:  3fff0c1c 00002ce0 3fff45a4 4020ec98 
3ffef670:  3fff0c1c 00002ce0 3fff45a4 4020d830 
3ffef680:  000005b4 000005b4 00000001 3ffef700 
3ffef690:  00000790 000005b4 000000f2 40100773 
3ffef6a0:  3fff0c1c 3fff0c1c 3ffef700 3ffef700 
3ffef6b0:  3fff0c1c 3fff0c1c 3ffef700 4020d8b7 
3ffef6c0:  00000000 3fff0c1c 3fff0c2c 402095

Danke!

**Comment by Aypac** [comment]
I assume the last comment is for #36 ?
Can you post it there again and include the exact code you used?

**Comment by Aypac** [comment]
Ok, I added a note [here](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/wiki/Understanding-error-messages) and [here](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/wiki/What-are-the-debug-levels-and-how-can-I-get-more-messages). Is that what you intended with this issue?

**Comment by Aypac** [comment]
Moin Roehrenkramladen,
meinst Du es sind noch weitere Schritte nötig?

**Comment by Roehrenkramladen** [comment]
Hallo,

habe es probiert, ohne Init kommt keine TR064 Verbindung zustande. Die Plazierung der Logindaten im Header ist kontraproduktiv. Das verhindert die Übergabe von Daten durch eine Eingabe. Man ist immer auf die hardcodierten Daten angewiesen.
