### ISSUE TITLE
legacy HTTPClient api usage 

### ISSUE THREAD

**Issue by coelner** [Aypac/Arduino-TR-064-SOAP-Library#40]
This uses the old api from the arduino/esp8266 and it is now forbidden (https://github.com/esp8266/Arduino/blob/34545a160da7c835aa87d7bace62192aee50fa78/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h#L164)
https://github.com/Aypac/Arduino-TR-064-SOAP-Library/blob/1e69e7ba585ac9ad602b19788d979ee00bc82244/src/tr064.cpp#L398

Maybe you should get a pointer to a wificlient instance or create your own.

**Comment by Aypac** [comment]
Thanks for the tip!
I'm not 100% sure what changes I need to implement.
Could you give a MWE of what you mean?

**Comment by Aypac** [comment]
Ah, I see. Looks like I basically only need to provide a reference to the WIFI client. Is that right? Do you, by any chance, know if this also works with LAN clients (relating to #35)?

**Comment by coelner** [comment]
Somehow I guess. You need something like this: https://github.com/khoih-prog/EthernetWebServer
because if you tell your library which Layer 2 instance to use, it needs to have a similiar api (or you have separate it with `#define` blocks).

**Comment by Aypac** [comment]
Is this covered by #49 ?

**Comment by coelner** [comment]
https://github.com/Aypac/Arduino-TR-064-SOAP-Library/blob/fbf75a50f16235d8dbf3ec0bcd420053c4aa2343/src/tr064.cpp#L455

It seems so. From #47 I can assume that it works with the esp8266 sdk

**Comment by Aypac** [comment]
Should be fixed in 3fb0d1b.
