### ISSUE TITLE
Tasmota/TR064

### ISSUE THREAD

**Issue by gsg2820** [Aypac/Arduino-TR-064-SOAP-Library#44]
i included the TR-064-SOAP-Library in my Tasmota Fork. Using the Tasmota Scriptor to send the commands.
working so far.
i made a lot of changes, mostly because i got a lot of "outoffmemory" errors. I'm not particularly good with C++ or with github, as matter of fact, so i don't know if and what i was doing the right way.
Maybe you want to have a look.

**Comment by Aypac** [comment]
I assume this is covered by the PR?

**Comment by gsg2820** [comment]
yes it is.
