### ISSUE TITLE
TR-064 and NodeMCU 1.0 (ESP-12E Module)

### ISSUE THREAD

**Issue by Mirandamurmel** [Aypac/Arduino-TR-064-SOAP-Library#51]
Hello,
I actually wanted to rebuild the project on https://www.reichelt.de/magazin/how-to/smarte-tuerklingel/. I have set everything as described on the page, but when I compile I always get the same error. When I compile the examples caller and home-indicator I get the same error:

C:\Users\Hans\Documents\Arduino\libraries\TR-064_SOAP_Library\src\tr064.cpp: In member function 'String TR064::httpRequest(String, String, String, bool)':

C:\Users\Hans\Documents\Arduino\libraries\TR-064_SOAP_Library\src\tr064.cpp:398:15: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, host, port, uri)

  398 |     http.begin(_ip, _port, url);

      |     ~~~~~~~~~~^~~~~~~~~~~~~~~~~

exit status 1

Fehler beim Kompilieren für das Board NodeMCU 1.0 (ESP-12E Module).

I wanted to ask whether the TR-064_SOAP_Library is still up to date?

Thank you.

**Comment by gsg2820** [comment]
Hello @Mirandamurmel

there's is a PR waiting for a review.

in the meantime you could try my fork.

**Comment by Mirandamurmel** [comment]
Hello gsg2820,

sorry i have not see issure #47 before. I have installed now the ESP8266 Board Version 2.7.4 an now it works.

Thank you for the fast reaction!

**Comment by f0rdprefect** [comment]
> Hello @Mirandamurmel
> 
> there's is a PR waiting for a review.
> 
> in the meantime you could try my fork.

Yes just had the same problem and using your fork made it compile. Now some testing!
