### ISSUE TITLE
Not building with newer versions of HTTPClient

### ISSUE THREAD

**Issue by MagEis** [Aypac/Arduino-TR-064-SOAP-Library#53]
The library is not building with newer versions of the HTTPClient-lib (or at least thats my guess). This can be fixed by adding a Wifi client to line 398 in tr064.cpp

#include` <WiFiClient.h>

String TR064::httpRequest(String url, String xml, String soapaction, bool retry) {
    deb_println("[HTTP] prepare request to URL: http://" + _ip + ":" + _port + url, DEBUG_INFO);
    WiFiClient wifiClient;
    HTTPClient http;
    http.begin(wifiClient, _ip, _port, url);

**Comment by Aypac** [comment]
Thanks. If I find some time I'll try to update it accordingly.

**Comment by Aypac** [comment]
Related to #40. Should be fixed in 3fb0d1b.
