### ISSUE TITLE
problem with latency in init/dial with lib V1.2.0

### ISSUE THREAD

**Issue by snug11** [Aypac/Arduino-TR-064-SOAP-Library#55]
hi René,
with the latest lib version i got a (perhaps latency) problem with the init & dial function with my combination:

Fritz!Box 6490 Cable
Fritz!OS 07.29
Fritz!Fon C4
NodeMCU Mini D1 (Clone)
Arduino 1.8.16
TR-064 SOAP 1.2.0

i am using the sketch from the linked reichelt article:
https://www.reichelt.de/magazin/how-to/smarte-tuerklingel/
it is working generally, but...

the functions:
**tr064_connection.init();** now last up to 10 seconds (without this, the code won`t work )
and the following:
**tr064_connection.action(tr064_service, "X_AVM-DE_DialNumber", call_params, 1);** this last further ~8-10s 

...to get a broadcast to the connected handhelds

could i do something to speed this up ?

**Comment by saak2820** [comment]
hi snug,
please enable debug and post the output.


you can Speed up with a direct call without calling init method at all.
please have a look at the caller.ino examples.

	// without loading available services through init() you have to set the url

connection.action("X_VoIP:1", "X_AVM-DE_DialNumber", params, 1, req, 0, "/upnp/control/x_voip");

**Comment by snug11** [comment]
hi,
now i`m using an ESP32 and the "caller.ino" with offered line. 
it`s running little faster (), but not like with the old lib version

my debug output:

`[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 1 - SCAN_DONE
[I][WiFiMulti.cpp:114] run(): [WIFI] scan done
[I][WiFiMulti.cpp:119] run(): [WIFI] 20 networks found
(- shorted list -)
[D][WiFiMulti.cpp:149] run():  --->   0: [6][44:4E:6D:84:C4:40] Mediastation (-46) *

[I][WiFiMulti.cpp:160] run(): [WIFI] Connecting BSSID: 44:4E:6D:84:C4:40 SSID: Mediastation Channel: 6 (-46)
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:419] _eventCallback(): STA IP: 192.168.178.107, MASK: 255.255.255.0, GW: 192.168.178.1
[I][WiFiMulti.cpp:174] run(): [WIFI] Connecting done.
[D][WiFiMulti.cpp:175] run(): [WIFI] SSID: Mediastation
[D][WiFiMulti.cpp:176] run(): [WIFI] IP: 192.168.178.107
[D][WiFiMulti.cpp:177] run(): [WIFI] MAC: 44:4E:6D:84:C4:40
[D][WiFiMulti.cpp:178] run(): [WIFI] Channel: 6

Button not pressed
Button not pressed
Button not pressed
Button not pressed
Button not pressed
Button pressed[TR064][action] with extraction
[TR064][cleanOldServiceName] searching for prefix in servicename: X_VoIP:1
[TR064][action_raw] with parameter, NewX_AVM-DE_PhoneNumber
[TR064][action_raw] with parametervalue, **611                                    (- solo handheld -)
[TR064][httpRequest] prepare request to URL: http://192.168.179.1:49000/upnp/control/x_voip
[TR064][httpRequest] Posting XML:
[TR064][httpRequest] ---------------------------------
<?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Header><h:InitChallenge xmlns:h="http://soap-authentication.org/digest/2001/10/" s:mustUnderstand="1"><UserID>ESP-Klingel</UserID></h:InitChallenge ></s:Header><s:Body><u:X_AVM-DE_DialNumber xmlns:u="urn:dslforum-org:service:X_VoIP:1"><NewX_AVM-DE_PhoneNumber>**611</NewX_AVM-DE_PhoneNumber></u:X_AVM-DE_DialNumber></s:Body></s:Envelope>
[TR064][httpRequest] ---------------------------------

[D][HTTPClient.cpp:579] sendRequest(): request type: 'POST' redirCount: 0

[D][HTTPClient.cpp:1125] connect():  connected to 192.168.179.1:49000
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'HTTP/1.1 200 OK'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'DATE: Wed, 29 Dec 2021 07:42:38 GMT'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'SERVER: FRITZ!Box 6490 Cable UPnP/1.0 AVM FRITZ!Box 6490 Cable 141.07.29'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'CONNECTION: keep-alive'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'CONTENT-LENGTH: 642'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'CONTENT-TYPE: text/xml; charset="utf-8"'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'EXT:'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: ''
[D][HTTPClient.cpp:1257] handleHeaderResponse(): code: 200
[D][HTTPClient.cpp:1260] handleHeaderResponse(): size: 642
[D][HTTPClient.cpp:603] sendRequest(): sendRequest code=200

[TR064][httpRequest] POST... SOAPACTION: 'urn:dslforum-org:service:X_VoIP:1#X_AVM-DE_DialNumber'
[TR064][httpRequest] Response code: 200
[TR064][xmlTakeParam] htmltag: ?xml version="1.0"?
[TR064][xmlTakeParam] htmltag: s:Header
[TR064][xmlTakeParam] htmltag: Status
[TR064][xmlTakeParam] Response status: unauthenticated
[TR064][xmlTakeParam] htmltag: Nonce
[TR064][xmlTakeParam] Extracted the nonce '21CE816DCBDE75FF' from the last respuest.
[TR064][xmlTakeParam] htmltag: Realm
[TR064][xmlTakeParam] Your secret is is 'ESP-Klingel:F!Box SOAP-Auth:xxxxxxxxxx'
[TR064][xmlTakeParam] Your hashed secret is 'e5cd700675cee4bc002ba92379xxxxxxx'
[TR064][xmlTakeParam] htmltag: /h:Challenge
[TR064][xmlTakeParam] htmltag: s:Body
[TR064][xmlTakeParam] htmltag: faultcode
[TR064][xmlTakeParam] htmltag: faultstring
[TR064][xmlTakeParam] htmltag: detail
[TR064][xmlTakeParam] htmltag: errorCode
[TR064][xmlTakeParam] <TR064> Failed, errorCode: '503'
[TR064][xmlTakeParam] <TR064> Failed, message: 'Authentication failed. No Secret in Header?'
[TR064][xmlTakeParam] htmltag: errorDescription
[TR064][xmlTakeParam] <TR064> Failed, errorDescription: 
[TR064][xmlTakeParam] htmltag: /UPnPError
[TR064][xmlTakeParam] htmltag: /s:Fault
[TR064][xmlTakeParam] htmltag: /s:Envelope                                (- from here, it take`s time -)
[TR064][action] extraction complete.
[TR064][action] Response status: unauthenticated, Tries: 0
[TR064][action] with extraction
[TR064][cleanOldServiceName] searching for prefix in servicename: X_VoIP:1
[TR064][generateAuthToken] The auth token is '99ad2015d18fd97d7b9fdd83d58c0da5'
[TR064][action_raw] with parameter, NewX_AVM-DE_PhoneNumber
[TR064][action_raw] with parametervalue, **611
[TR064][httpRequest] prepare request to URL: http://192.168.179.1:49000/upnp/control/x_voip
[TR064][httpRequest] Posting XML:
[TR064][httpRequest] ---------------------------------
<?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Header><h:ClientAuth xmlns:h="http://soap-authentication.org/digest/2001/10/" s:mustUnderstand="1"><Nonce>21CE816DCBDE75FF</Nonce><Auth>99ad2015d18fd97d7b9fdd83d58c0da5</Auth><UserID>ESP-Klingel</UserID><Realm>F!Box SOAP-Auth</Realm></h:ClientAuth></s:Header><s:Body><u:X_AVM-DE_DialNumber xmlns:u="urn:dslforum-org:service:X_VoIP:1"><NewX_AVM-DE_PhoneNumber>**611</NewX_AVM-DE_PhoneNumber></u:X_AVM-DE_DialNumber></s:Body></s:Envelope>
[TR064][httpRequest] ---------------------------------

[D][HTTPClient.cpp:579] sendRequest(): request type: 'POST' redirCount: 0

[D][HTTPClient.cpp:1085] connect(): already connected, reusing connection
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'HTTP/1.1 200 OK'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'DATE: Wed, 29 Dec 2021 07:42:49 GMT'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'SERVER: FRITZ!Box 6490 Cable UPnP/1.0 AVM FRITZ!Box 6490 Cable 141.07.29'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'CONNECTION: keep-alive'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'CONTENT-LENGTH: 520'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'CONTENT-TYPE: text/xml; charset="utf-8"'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: 'EXT:'
[V][HTTPClient.cpp:1216] handleHeaderResponse(): RX: ''
[D][HTTPClient.cpp:1257] handleHeaderResponse(): code: 200
[D][HTTPClient.cpp:1260] handleHeaderResponse(): size: 520
[D][HTTPClient.cpp:603] sendRequest(): sendRequest code=200

[TR064][httpRequest] POST... SOAPACTION: 'urn:dslforum-org:service:X_VoIP:1#X_AVM-DE_DialNumber'
[TR064][httpRequest] Response code: 200
[TR064][xmlTakeParam] htmltag: ?xml version="1.0"?
[TR064][xmlTakeParam] htmltag: s:Header
[TR064][xmlTakeParam] htmltag: Status
[TR064][xmlTakeParam] Response status: authenticated
[TR064][xmlTakeParam] htmltag: Nonce
[TR064][xmlTakeParam] Extracted the nonce '45DAD20E0E23A12E' from the last respuest.
[TR064][xmlTakeParam] htmltag: Realm
[TR064][xmlTakeParam] htmltag: /h:NextChallenge
[TR064][xmlTakeParam] htmltag: s:Body
[TR064][xmlTakeParam] htmltag: /u:X_AVM-DE_DialNumberResponse
[TR064][xmlTakeParam] htmltag: /s:Envelope
[TR064][action] extraction complete.
[TR064][action] Response status: authenticated, Tries: 0
[TR064][action] Done.
[D][HTTPClient.cpp:385] disconnect(): tcp keep open for reuse

Button not pressed
Button not pressed
Button not pressed
Button not pressed`

**Comment by saak2820** [comment]
hi,

so the code works?

how fast is it now without debug?

**Comment by snug11** [comment]
yes, this code is working (caller.ino)
https://www.youtube.com/watch?v=trqjsp4ZbbE

/**
 * caller.ino
 *  Oliver-André Urban
 *   based on
 *    home-indicator.ino
 *      by René Vollmer
 * 
 *  Example code for placing internal DECT phone calls
 * 
 *  Please adjust your data below.
 *  
 *  created on: 07.06.2017
 *  latest update: 11.06.2019
 */

#include <Arduino.h>
#if defined(ESP8266)
	//Imports for ESP8266
	#include <ESP8266WiFi.h>
	#include <ESP8266WiFiMulti.h>
	#include <ESP8266HTTPClient.h>
	ESP8266WiFiMulti WiFiMulti;
#elif defined(ESP32)
	//Imports for ESP32
	#include <WiFi.h>
	#include <WiFiMulti.h>
	#include <HTTPClient.h>
	WiFiMulti WiFiMulti;
#endif

#include <tr064.h>


// Flash BUTTON - you can connect a separate button to this pin or an opto-coupler 
// for example: use a resistor and an opto-coupler to connect to a doorbell
#define BUTTON 15


//-------------------------------------------------------------------------------------
// Put your router settings here
//-------------------------------------------------------------------------------------

// Wifi network name (SSID)
const char* wifi_ssid = "xxx"; 

// Wifi network password
const char* wifi_password = "xxx";

// The username if you created an account, "admin" otherwise
const char* fuser = "ESP-Klingel";

// The password for the aforementioned account.
const char* fpass = "xxx";

// IP address of your router. This should be "192.168.179.1" for most FRITZ!Boxes
const char* IP = "192.168.179.1";

// Port of the API of your router. This should be 49000 for all TR-064 devices.
const int PORT = 49000;

// -------------------------------------------------------------------------------------

// TR-064 connection
TR064 connection(PORT, IP, fuser, fpass);


void setup() {
	Serial.begin(115200);
	// Wait a few secs for warm-up (dunno why, was in the default code for http connections).
	delay(5000);

	// Connect to wifi
	ensureWIFIConnection();
	
	// Port as input
	pinMode(BUTTON, INPUT_PULLUP);
}

void loop() {
	int button_state = digitalRead(BUTTON);
	if (digitalRead(BUTTON) == LOW) {
		if (Serial) {
			Serial.println();
			Serial.printf("Button pressed");
		}
		callWahlhilfe();
		// callDect();
		// char* status=getStatus();
		delay(20000);
	} else {
		if (Serial) {
			Serial.println();
			Serial.printf("Button not pressed");
		}
		delay(500);
	}
}


void callWahlhilfe() {
	ensureWIFIConnection();

	String params[][2] = {{"NewX_AVM-DE_PhoneNumber", "**611"}}; //799
	String req[][2] = {{}};

	//connection.action("urn:dslforum-org:service:X_VoIP:1", "X_AVM-DE_DialNumber", params, 1, req, 0);
  connection.action("X_VoIP:1", "X_AVM-DE_DialNumber", params, 1, req, 0, "/upnp/control/x_voip");
}

void callDect() {
	ensureWIFIConnection();

	String params[][2] = {{"NewAIN", "12345 0123456"}, {"NewSwitchState", "TOGGLE"}};
	connection.action("urn:dslforum-org:service:X_AVM-DE_Homeauto:1", "SetSwitch", params, 2);
}

String getStatus() {
	String paramsb[][2] = {{"NewAIN", "12345 0123456"}};
	String reqb[][2] = {{"NewDeviceId", ""}, {"NewSwitchState", ""}};
	connection.action("urn:dslforum-org:service:X_AVM-DE_Homeauto:1", "GetSpecificDeviceInfos", paramsb, 1, reqb, 2);
	return reqb[1][1];
}


/**
 * Makes sure there is a WIFI connection and waits until it is (re-)established.
 */
void ensureWIFIConnection() {
	if ((WiFiMulti.run() != WL_CONNECTED)) {
		WiFiMulti.addAP(wifi_ssid, wifi_password);
		while ((WiFiMulti.run() != WL_CONNECTED)) {
			delay(100);
		}
	}
}

**Comment by saak2820** [comment]
Ok.
I have to take a look. Can take a while.

How about the second call when the Authentication is done.

**Comment by saak2820** [comment]
Authentication is happening on first call. so after that the Cal's should be faster.

**Comment by snug11** [comment]
...from my "feeling", there`s absolute no change in time from the first to the following calls/button press.
did you try it by yourself - did you got faster reaction than my setup ?

so in meantime, i am using again the older lib and older/working esp-version in the boardmanager - that combination work`s fine for me like my wish, even when it could be a possible security topic.

thank you so much for your time and activity for me !  :-)

**Comment by saak2820** [comment]
you were right. parsing the XML ends in a timeout and causes the delay.
pull request #56 sets the value to 40 milliseconds.

**Comment by saak2820** [comment]
it is not the function from client it is from Stream. and it is milliseconds.

**Comment by ArminJo** [comment]
Sorry, please but take another look
What you intended is `stream->Stream::setTimeout(40);`


And  my log also logs a 40 second timeout. The first number is the milliseconds.
```
[ 21684][V][tr064.cpp:608] xmlTakeParam(): </s:Fault>
[ 61688][V][tr064.cpp:608] xmlTakeParam(): </s:Envelope>
```
40000 milliseconds wait here!
```
[101688][V][tr064.cpp:254] action(): Extraction complete
[101688][I][tr064.cpp:258] action(): Response status: unauthenticated, tries: 0 
```

**Comment by saak2820** [comment]
maybe there is something different in my setup. But thank you for the response.
is the change working for you.

**Comment by ArminJo** [comment]
Yes, with the change I have no delay!
```
[ 27184][V][tr064.cpp:599] xmlTakeParam(): </s:Envelope>
[ 27224][V][tr064.cpp:266] action(): Extraction complete
```

**Comment by thncode** [comment]
@saak2820 saved my setup too, KUDOS!

**Comment by ArminJo** [comment]
I think, this issue can be closed now 😀 
Thanks
Armin

**Comment by Aypac** [comment]
Closed. Will merge PR #58 later.
