### ISSUE TITLE
Bad Folder Structure when using Arduino IDE

### ISSUE THREAD

**Issue by hasenradball** [Aypac/Arduino-TR-064-SOAP-Library#6]
Hi,
I tried to use git to add this Library in the Arduino IDE by using the command:
```
git clone https://github.com/Aypac/Arduino-TR-064-SOAP-Library.git Arduino-TR-SOAP-Library
```
The cloning was successfull, but the Problem was that during build the Header file tr064.h was not found.
The *.h and the *.cpp has to moved one folder above, so that the IDE could build the file.
So please move the files <tr064.h>, <tr064.cpp> and the file <library.properties> one folder up and delete the empty folder named "TR-064-SOAP-Library".

Benefit:
the the build works directly by using git for clone the repository and the git pull also works for update changes from the repository.

Good example:
see: https://github.com/PaulStoffregen/Time
Works fine using git clone and git pull, etc...

Thank you!

**Comment by Aypac** [comment]
Done with 5aed7d4

**Comment by hasenradball** [comment]
Hi Thank you!

Perfect!
One Question regarding the code related to <Serial.print>
What is the benefit of the ```#define Use_Serial Serial``` instead of using directly ```Serial``` in the *.cpp file?.

**Comment by Aypac** [comment]
Hi!
My pleasure :)

Thank you for your suggestions! Keep 'em coming!

I honestly don't know. I guess I adopted it from somewhere else. But I have to change that anyways, see #8.
If you want to do this, an according pull-request would be very welcome. It might be some time otherwise, before I come around to do this.

**Comment by hasenradball** [comment]
Hi I proposed some changes see PR #13.
