### ISSUE TITLE
Is this a typo? In the commit before it has been spelled differently "serviceType" not "sErviceType" ... 

### ISSUE THREAD

**Issue by gremmlinMTW** [Aypac/Arduino-TR-064-SOAP-Library#64]
https://github.com/Aypac/Arduino-TR-064-SOAP-Library/blob/7469e9ee3e1042e38e2ca86f85c707eda881b4f7/src/tr064.cpp#L128

**Comment by Aypac** [comment]
Yes, I think this is an old typo resurfacing through the wonders of git merging/cherry-picking.
However, it should not matter, because if I remember right, `xmlTakeParam` reverts to a non-case-sensitive version if the case-sensitive one does not work. I will double-check to be sure.

**Comment by gremmlinMTW** [comment]
You are right, I saw that just later. Best regards, Roland

René Vollmer ***@***.***> schrieb am Di. 21. Feb. 2023 um
22:22:

**Comment by Aypac** [comment]
Still fixed it in [cbb7223](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/commit/cbb7223d177e9cb0bb59e62f49bc0aeb98af57c1) / release 1.2.3
